### ISSUE TITLE
What is authentication and 2FA?

### ISSUE THREAD

**Issue by fxyzbtc** [Timmy49/Hello-Git#2]

**Comment by Timmy49** [comment]
Authentication is verifying the identity of someone or something, making sure that whoever is accessing is the right person. Usually, authentication is used in the form of a username and password where the user needs to fill in certain credentials to verify their identity.

2FA, short for 2 factor authentication, is simply another process of authentication to further ensure safety and make sure that the identity of someone really is theirs. For example, after entering a password, the user will be greeted with another process of verification like a confirmation message send to the official users phone number or another password but in a different form. Details such as birthday or a choice of your own verification method set by the user can also be used in some circumstances. 2FA significantly enhances security because even if your password is compromised, the person trying to access something requiring your identity / attacker would still need the second verification to gain access.
